In [1]:
import pandas as pd

In [7]:
df = pd.read_csv('analystFinal2.csv')

In [3]:
def parseSalario(s):
    s2 = s.replace('$','')
    commaIdx = s2.find(',')
    final = s2[:commaIdx]
    #print(final)
    #return int(final)
    return final

In [5]:
df['Salario'] = df['Salario'].map(parseSalario)

In [6]:
df['Salario'] = pd.to_numeric(df['Salario'])

ValueError: Unable to parse string "A conveni" at position 4

In [8]:
df['Jornada'] = df['Jornada'].apply(lambda x: x.upper())

In [9]:
def parseDate(d):
    idx = d.find("-")
    dParse = d[:idx]
    return dParse

In [10]:
df['Activo desde'] = df['Activo desde'].map(parseDate)

In [12]:
df['Activo desde'] = pd.to_datetime(df['Activo desde'], dayfirst=True)

In [13]:
df

,id,Nombre de trabajo,Compania,Salario,Categoria,Subcategoria,Localidad,Activo desde,Jornada,Tipo de contrato
0,0,Se necesita personal de 17 a 35 años,EMPLEOS EN GUAYAQUIL,"$ 500,00 (Mensual)",Almacenamiento / Logística / Distribución,Oficios y Profesiones,Guayaquil,2020-08-16,TIEMPO COMPLETO,Contrato a Plazo Indeterminado
1,1,Auxiliar de bodega,PARTESCAT,"500,00 US$ (Neto mensual)",Almacenamiento / Logística / Distribución,Logística y Distribución,Quito,2020-08-16,TIEMPO COMPLETO,Otro tipo de contrato
2,2,Chofer y oficial,Pluproxsa S.A.,"406,00 US$ (Neto mensual)",Almacenamiento / Logística / Distribución,Logística y Distribución,Guayaquil,2020-08-16,TIEMPO COMPLETO,Contrato por tiempo indefinido
3,3,Mecánico Motocicletas,MULTIMOTOS S. A.,"394,00 US$ (Neto mensual)",Almacenamiento / Logística / Distribución,Mantenimiento y Reparaciones,Portoviejo,2020-08-16,TIEMPO COMPLETO,Contrato por tiempo indefinido
4,4,Mecánico,CONFIDENCIAL,A convenir,Almacenamiento / Logística / Distribución,Mantenimiento y Reparaciones,Manta,2020-08-16,TIEMPO COMPLETO,Contrato por tiempo indefinido
...,...,...,...,...,...,...,...,...,...,...
902,902,Asistente de directorio,Salinas Yacht Club,"480,00 US$ (Neto mensual)",Administración / Contabilidad / Finanzas,Administración,Guayaquil,2020-07-28,TIEMPO COMPLETO,Contrato por tiempo indefinido
903,903,Jefe administrativo,Segumar sci s a,A convenir,Administración / Contabilidad / Finanzas,Administración,Latacunga,2020-07-27,TIEMPO COMPLETO,Contrato por tiempo indefinido
904,904,Gerente de Operaciones,GRUPO AK,A convenir,Administración / Contabilidad / Finanzas,Administración,Guayaquil,2020-07-27,TIEMPO COMPLETO,Contrato por tiempo indefinido
905,905,Asistente contable,Henry sport,A convenir,Administración / Contabilidad / Finanzas,Contabilidad / Finanzas,Quito,2020-07-27,TIEMPO COMPLETO,Contrato por tiempo indefinido
906,906,Coordinación de Marketing y Operaciones,CONFIDENCIAL,"850,00 US$ (Neto mensual)",Administración / Contabilidad / Finanzas,Administración,Guayaquil,2020-07-27,TIEMPO COMPLETO,Contrato por tiempo indefinido

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 907 entries, 0 to 906
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 907 non-null    int64
 1   Nombre de trabajo  907 non-null    object
 2   Compania           907 non-null    object
 3   Salario            907 non-null    object
 4   Categoria          907 non-null    object
 5   Subcategoria       907 non-null    object
 6   Localidad          907 non-null    object
 7   Activo desde       907 non-null    datetime64[ns]
 8   Jornada            907 non-null    object
 9   Tipo de contrato   907 non-null    object
dtypes: datetime64[ns](1), int64(1), object(8)
memory usage: 71.0+ KB

In [15]:
df.to_csv('dataP.csv', index=False)